version: '3'
services:
  app:
    build: .
    ports:
      - "4000"
    networks:
      - "appnetwork"
    labels:
      - "traefik.backend=app"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:localhost"
  lb:
    image: traefik:1.7
    command: -c /dev/null --web --docker --docker.domain=localhost --logLevel=INFO 
    ports:
      - 4000:80
      - 8080:8080
    networks:
      - "appnetwork"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  appnetwork: